# state.py
from typing import TypedDict, List, Optional, Dict

class ForgeState(TypedDict):
    """
    This is the central memory of our system.
    Agents read from and write to this dictionary.
    """
    # The initial instruction from the user.
    task: str
    
    # The multi-step plan generated by the Planner Agent.
    # This is now a list of dictionaries, where each dictionary is a specific command.
    # e.g., [{"command": "CREATE_FILE", "path": "file.py"}]
    plan: Optional[List[Dict]]
    
    # A counter for which step the Coder Agent is currently on.
    current_step: int

    # A field to store the successful result of the last operation.
    result: Optional[str]

    # A field to store an error message if something fails.
    error: Optional[str]